import React from 'react';
import { 
  ShieldCheck, 
  FileText, 
  Download, 
  Clock, 
  Zap, 
  CheckCircle2,
  Activity,
  Globe
} from 'lucide-react';
import { motion } from 'framer-motion';
import { useSosStore } from '../store';
import { IRADReportCard } from './iRADReportCard';

interface TimelineEvent {
  time: string;
  title: string;
  detail: string;
  status: 'critical' | 'caution' | 'success';
}

const timelineData: TimelineEvent[] = [
  { time: '14:23:01', title: 'Crash detected', detail: '12.4G impact recorded by onboard sensors', status: 'critical' },
  { time: '14:23:11', title: '10s consciousness countdown completed', detail: 'No user intervention detected after alert', status: 'caution' },
  { time: '14:23:12', title: 'AI triage initiated', detail: 'Case ID: SOS-ALPHA-982 assigned', status: 'success' },
  { time: '14:23:19', title: 'Voice stress detected', detail: 'Panic Score 87/100 — adjusting triage to CRITICAL', status: 'critical' },
  { time: '14:23:35', title: 'Medical profile decrypted', detail: 'AES-GCM 256-bit secure decryption successful', status: 'success' },
  { time: '14:23:47', title: 'Nearest ALS unit dispatched', detail: 'Unit A47 dispatched (ETA 4m 12s)', status: 'success' },
  { time: '14:24:02', title: 'Hospital pre-alerted', detail: 'St. Mary’s Trauma Bay reserved', status: 'success' },
  { time: '14:27:59', title: 'Unit A47 on scene', detail: 'Arrival confirmed by geolocation', status: 'success' },
  { time: '14:28:01', title: 'Golden Hour Status', detail: '31m 59s remaining for optimal survival', status: 'caution' },
  { time: '14:45:22', title: 'Patient stabilized', detail: 'Final report generated by field unit', status: 'success' },
];

export const IncidentTimeline: React.FC = () => {
  const { iradReport, iradAckId } = useSosStore();
  const handleExport = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 p-4 sm:p-8 font-sans print:bg-white print:text-black">
      {/* Print Styles */}
      <style>{`
        @media print {
          @page { size: A4; margin: 20mm; }
          body { -webkit-print-color-adjust: exact; background-color: white !important; color: black !important; }
          .no-print { display: none !important; }
          .print-border { border: 1px solid #e2e8f0 !important; }
          .print-shadow { box-shadow: none !important; }
        }
      `}</style>

      {/* Report Header */}
      <div className="max-w-4xl mx-auto space-y-8">
        <div className="flex flex-col sm:flex-row sm:items-end justify-between border-b border-white/10 pb-6 gap-6 print:border-slate-300">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="bg-red-600 p-2 rounded shadow-lg shadow-red-600/20">
                <ShieldCheck size={24} className="text-white" />
              </div>
              <h1 className="text-3xl font-black tracking-tighter uppercase italic print:not-italic">ROADSoS Incident Report</h1>
            </div>
            <p className="text-slate-400 font-mono text-sm print:text-slate-600 uppercase tracking-widest">
              OFFICIAL EMERGENCY RESPONSE RECORD • #SOS-ALPHA-982
            </p>
          </div>
          
          <button 
            onClick={handleExport}
            className="no-print flex items-center gap-2 bg-white/5 hover:bg-white/10 border border-white/10 px-4 py-2 rounded-[var(--radius-lg)] font-bold text-sm transition-all"
          >
            <Download size={16} />
            EXPORT PDF
          </button>
        </div>

        {/* Summary Stats */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 print:gap-2">
          {[
            { label: 'Total response time', value: '4m 58s', icon: <Clock size={16} />, color: 'text-blue-400' },
            { label: 'AI saved estimated', value: '8.3 minutes', icon: <Zap size={16} />, color: 'text-emerald-400' },
            { label: 'Outcome', value: 'Stabilized', icon: <CheckCircle2 size={16} />, color: 'text-emerald-500' },
          ].map((stat, i) => (
            <div key={i} className="bg-white/5 p-4 rounded-xl border border-white/5 print:border-slate-200 print:bg-slate-50 print-shadow">
              <div className="flex items-center gap-2 text-slate-500 text-[10px] uppercase font-black tracking-widest mb-1 print:text-slate-500">
                {stat.icon}
                {stat.label}
              </div>
              <div className={`text-xl font-black ${stat.color} print:text-slate-900`}>
                {stat.value}
              </div>
            </div>
          ))}
        </div>

        {/* Timeline Section */}
        <div className="bg-white/2 border border-white/5 rounded-2xl p-6 sm:p-10 print:border-slate-200 print:bg-white">
          <div className="flex items-center gap-2 mb-10 pb-4 border-b border-white/5 print:border-slate-100">
            <FileText size={18} className="text-slate-400" />
            <h2 className="font-bold text-lg uppercase tracking-tight">Detailed Incident Sequence</h2>
          </div>

          <div className="relative">
            {/* Connecting Line */}
            <div className="absolute left-[92px] sm:left-[112px] top-2 bottom-2 w-px bg-slate-800 print:bg-slate-200" />

            <div className="space-y-12">
              {timelineData.map((event, i) => (
                <motion.div 
                  initial={{ opacity: 0, x: -10 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  key={i} 
                  className="relative flex items-start group"
                >
                  {/* Time */}
                  <div className="w-[80px] sm:w-[100px] pt-1 text-right pr-6 sm:pr-8">
                    <span className="font-mono text-xs text-slate-500 font-bold group-hover:text-slate-300 transition-colors print:text-slate-600">
                      {event.time}
                    </span>
                  </div>

                  {/* Dot */}
                  <div className="absolute left-[92px] sm:left-[112px] -translate-x-1/2 mt-1.5 z-10">
                    <div className={`w-3 h-3 rounded-full border-4 border-slate-950 transition-all group-hover:scale-125 print:border-white ${
                      event.status === 'critical' ? 'bg-red-500 shadow-[0_0_10px_rgba(239,68,68,0.5)] print:shadow-none' :
                      event.status === 'caution' ? 'bg-amber-500 shadow-[0_0_10px_rgba(245,158,11,0.5)] print:shadow-none' :
                      'bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,0.5)] print:shadow-none'
                    }`} />
                  </div>

                  {/* Description */}
                  <div className="flex-1 pl-10 sm:pl-12">
                    <h3 className={`font-black text-sm uppercase tracking-tight mb-0.5 ${
                      event.status === 'critical' ? 'text-red-400' :
                      event.status === 'caution' ? 'text-amber-400' :
                      'text-slate-200 print:text-slate-900'
                    }`}>
                      {event.title}
                    </h3>
                    <p className="text-slate-500 text-sm leading-relaxed print:text-slate-600">
                      {event.detail}
                    </p>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </div>

        {/* iRAD MoRTH Filing Section */}
        {iradReport && iradAckId && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mt-12"
          >
            <div className="flex items-center gap-2 mb-6 px-4">
              <Globe size={18} className="text-emerald-500" />
              <h2 className="font-bold text-lg uppercase tracking-tight text-white">Government Compliance Filing</h2>
            </div>
            <IRADReportCard report={iradReport} ackId={iradAckId} />
          </motion.div>
        )}

        {/* Footer */}
        <div className="border-t border-white/5 pt-6 flex flex-col sm:flex-row justify-between items-center text-[10px] text-slate-600 uppercase font-bold tracking-widest gap-4 print:border-slate-200">
          <div className="flex items-center gap-4">
            <span className="flex items-center gap-1.5">
              <Activity size={12} className="text-emerald-500" />
              SYSTEM STATUS: NOMINAL
            </span>
            <span className="hidden sm:inline opacity-20">|</span>
            <span>DATA ENCRYPTION: AES-256-GCM</span>
          </div>
          <div className="text-right">
            GENERATED BY ROADSOS AI • {new Date().toLocaleDateString()}
          </div>
        </div>
      </div>
    </div>
  );
};
