import { useParams } from 'react-router-dom';
import { useState, useEffect } from 'react';
import { Clock, MapPin, Activity, MessageSquare, AlertTriangle, Info, Send } from 'lucide-react';
import { MapContainer, TileLayer, Marker, Popup, Circle } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

// Fix for default marker icons
import iconUrl from 'leaflet/dist/images/marker-icon.png';
import iconRetinaUrl from 'leaflet/dist/images/marker-icon-2x.png';
import shadowUrl from 'leaflet/dist/images/marker-shadow.png';

// @ts-expect-error Leaflet default icon fix
delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl,
  iconUrl,
  shadowUrl,
});

export const FamilyTracker = () => {
  const { incidentId } = useParams();
  const [timelineIndex, setTimelineIndex] = useState(0);
  const [chatMessage, setChatMessage] = useState('');
  const [messages, setMessages] = useState<{sender: 'system' | 'family', text: string, time: string}[]>([
    { sender: 'system', text: 'This channel is monitored by ROADSoS dispatchers.', time: new Date().toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'}) }
  ]);

  // Mock timeline progression
  useEffect(() => {
    const timer1 = setTimeout(() => setTimelineIndex(1), 3000);
    const timer2 = setTimeout(() => setTimelineIndex(2), 8000);
    const timer3 = setTimeout(() => setTimelineIndex(3), 15000);
    return () => { clearTimeout(timer1); clearTimeout(timer2); clearTimeout(timer3); };
  }, []);

  const timelineSteps = [
    { label: 'SOS Received', time: '10:42 AM', desc: 'Alert automatically generated by device' },
    { label: 'Unit Dispatched', time: '10:44 AM', desc: 'Ambulance DL-1CA-4822 en route' },
    { label: 'Unit Arrived', time: '10:51 AM', desc: 'Responders on scene' },
    { label: 'In Transit to Hospital', time: '11:05 AM', desc: 'Transporting to AIIMS Delhi' },
  ];

  const handleSendMessage = (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatMessage.trim()) return;
    setMessages([...messages, { sender: 'family', text: chatMessage, time: new Date().toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'}) }]);
    setChatMessage('');
    
    // Mock reply
    setTimeout(() => {
      setMessages(prev => [...prev, { sender: 'system', text: 'Dispatcher received your message.', time: new Date().toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'}) }]);
    }, 1500);
  };

  return (
    <div className="min-h-screen bg-gray-50 font-sans text-gray-900 pb-20 selection:bg-blue-100">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 sticky top-0 z-50">
        <div className="max-w-3xl mx-auto px-4 py-4 flex justify-between items-center">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-blue-600 text-white rounded-lg flex items-center justify-center font-black text-xl shadow-sm">R</div>
            <div>
              <h1 className="text-lg font-bold text-gray-900 leading-tight">ROADSoS Tracker</h1>
              <p className="text-xs font-medium text-gray-500 uppercase tracking-widest">Incident {incidentId || 'INC-001'}</p>
            </div>
          </div>
          <div className="flex items-center gap-2 bg-blue-50 text-blue-700 px-3 py-1.5 rounded-full text-xs font-bold uppercase">
            <div className="w-2 h-2 bg-blue-600 rounded-full animate-pulse" />
            Live
          </div>
        </div>
      </header>

      {/* Privacy Notice */}
      <div className="bg-amber-50 border-b border-amber-100 px-4 py-3">
        <div className="max-w-3xl mx-auto flex items-start gap-3">
          <Info className="text-amber-600 mt-0.5" size={18} />
          <div>
            <p className="text-sm text-amber-900 font-medium">Privacy Notice</p>
            <p className="text-xs text-amber-700 mt-0.5">This link will expire in 24 hours. For privacy, only logistical routing information is shown. Medical details are restricted to authorized personnel.</p>
          </div>
        </div>
      </div>

      <main className="max-w-3xl mx-auto px-4 mt-8 space-y-8">
        
        {/* Triage Overview */}
        <section className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
          <div className="flex items-center gap-2 mb-4 text-red-600">
            <Activity size={20} />
            <h2 className="font-bold text-lg text-gray-900">Current Status</h2>
          </div>
          
          <div className="flex flex-col md:flex-row gap-6">
            <div className="flex-1">
              <div className="inline-flex items-center gap-2 bg-red-50 text-red-700 px-3 py-1 rounded-md text-sm font-bold mb-3">
                <AlertTriangle size={16} /> PRIORITY 1
              </div>
              <p className="text-gray-600 text-sm leading-relaxed mb-4">
                The ROADSoS AI triage has classified this incident as high priority. Emergency services have been deployed.
              </p>
            </div>
          </div>
        </section>

        {/* Timeline */}
        <section className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
          <div className="flex items-center gap-2 mb-6 text-blue-600">
            <Clock size={20} />
            <h2 className="font-bold text-lg text-gray-900">Timeline</h2>
          </div>

          <div className="relative border-l-2 border-gray-100 ml-3 space-y-8 pb-4">
            {timelineSteps.map((step, idx) => (
              <div key={idx} className={`relative pl-8 transition-opacity duration-500 ${idx > timelineIndex ? 'opacity-40' : 'opacity-100'}`}>
                {/* Node */}
                <div className={`absolute -left-[9px] top-1 w-4 h-4 rounded-full border-2 border-white ${idx < timelineIndex ? 'bg-blue-600' : idx === timelineIndex ? 'bg-blue-600 animate-ping' : 'bg-gray-300'}`} />
                {idx === timelineIndex && <div className="absolute -left-[9px] top-1 w-4 h-4 rounded-full bg-blue-600" />}

                <div>
                  <div className="flex items-baseline gap-2">
                    <h3 className={`font-bold ${idx <= timelineIndex ? 'text-gray-900' : 'text-gray-500'}`}>{step.label}</h3>
                    {idx <= timelineIndex && <span className="text-xs font-semibold text-blue-600">{step.time}</span>}
                  </div>
                  <p className="text-sm text-gray-500 mt-1">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Map */}
        <section className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6 overflow-hidden">
          <div className="flex justify-between items-end mb-4">
            <div className="flex items-center gap-2 text-green-600">
              <MapPin size={20} />
              <h2 className="font-bold text-lg text-gray-900">Destination Hospital</h2>
            </div>
            <div className="text-right">
              <p className="font-bold text-gray-900">AIIMS Delhi</p>
              <p className="text-xs text-gray-500">Estimated Arrival: 11:15 AM</p>
            </div>
          </div>
          
          <div className="h-[250px] w-full rounded-xl overflow-hidden bg-gray-100 relative z-0">
             <MapContainer center={[28.5672, 77.2100]} zoom={13} style={{ height: '100%', width: '100%' }} zoomControl={false} dragging={false}>
               <TileLayer
                 url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png"
                 attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
               />
               <Marker position={[28.5672, 77.2100]}>
                  <Popup>Destination: AIIMS</Popup>
               </Marker>
               <Circle center={[28.5672, 77.2100]} pathOptions={{ fillColor: 'green', fillOpacity: 0.2, color: 'green', weight: 1 }} radius={500} />
             </MapContainer>
          </div>
        </section>

        {/* Chat */}
        <section className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6 flex flex-col">
          <div className="flex items-center gap-2 mb-4 text-purple-600">
            <MessageSquare size={20} />
            <h2 className="font-bold text-lg text-gray-900">Dispatcher Contact</h2>
          </div>

          <div className="bg-gray-50 rounded-xl p-4 flex-1 h-[200px] overflow-y-auto mb-4 border border-gray-100 flex flex-col gap-3">
             {messages.map((msg, i) => (
                <div key={i} className={`flex flex-col ${msg.sender === 'family' ? 'items-end' : 'items-start'}`}>
                  <div className={`px-4 py-2 rounded-2xl max-w-[80%] text-sm ${msg.sender === 'family' ? 'bg-blue-600 text-white rounded-tr-sm' : 'bg-white border border-gray-200 text-gray-800 rounded-tl-sm'}`}>
                    {msg.text}
                  </div>
                  <span className="text-[10px] text-gray-400 mt-1 px-1">{msg.time}</span>
                </div>
             ))}
          </div>

          <form onSubmit={handleSendMessage} className="flex gap-2">
            <input 
              type="text" 
              value={chatMessage}
              onChange={(e) => setChatMessage(e.target.value)}
              placeholder="Ask for an update..." 
              className="flex-1 border border-gray-300 rounded-lg px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all bg-white text-gray-900 placeholder-gray-400"
            />
            <button 
              type="submit" 
              className="bg-blue-600 hover:bg-blue-700 text-white p-2 rounded-lg transition-colors flex items-center justify-center min-w-[40px]"
            >
              <Send size={18} />
            </button>
          </form>
        </section>

      </main>
    </div>
  );
};
