/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { logger } from './lib/logger';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Handle Push Events
self.addEventListener('push', (event: PushEvent) => {
  if (!event.data) return;

  try {
    const payload = event.data.json();
    const { title, body, icon, badge, data } = payload;

    const options = {
      body: body || 'Emergency Alert nearby.',
      icon: icon || '/pwa-192x192.svg',
      badge: badge || '/pwa-192x192.svg',
      vibrate: [200, 100, 200, 100, 200, 100, 400],
      data: data || {},
      actions: [
        { action: 'respond', title: 'Respond Now' },
        { action: 'dismiss', title: 'Dismiss' }
      ]
    };

    event.waitUntil(
      self.registration.showNotification(title || '🚨 ROADSoS ALERT', options)
    );
  } catch (err) {
    logger.error('Push payload parsing failed:', err);
  }
});

// Handle Notification Clicks
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  const { action, notification } = event;
  notification.close();

  if (action === 'respond') {
    const url = notification.data?.responderUrl || '/';
    
    event.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
        // If a window is already open, focus it
        for (const client of clientList) {
          if ('focus' in client) return client.focus();
        }
        // Otherwise open a new window
        if (self.clients.openWindow) return self.clients.openWindow(url);
      })
    );
  }
});
