import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface IncidentReportData {
  id: string;
  timestamp: string;
  location: { lat: number; lng: number };
  detectionMethod: 'G-Force' | 'Manual' | 'Voice' | 'Automatic';
  aiTriage: {
    severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    confidence: number;
    recommendedUnit: 'ALS' | 'BLS';
    summary: string;
  };
  timeline: Array<{
    time: string;
    event: string;
    responder: string;
    status: string;
  }>;
  resources: Array<{
    name: string;
    type: string;
    eta: string;
    actualArrival: string;
    responseTime: string;
  }>;
  victimData: {
    ageRange: string;
    injuries: string[];
    consciousness: string;
  };
}

export const generateIncidentPDF = async (data: IncidentReportData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // Header blue band
  doc.setFillColor(0, 51, 153); // Deep Blue
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('ROADSOS INCIDENT REPORT', 14, 20);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Incident ID: ${data.id}`, 14, 30);
  doc.text('IIT Madras Road Safety Hackathon 2026', pageWidth - 14, 30, { align: 'right' });

  let currentY = 50;

  // Section 1: Incident Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('1. Incident Overview', 14, currentY);
  currentY += 10;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Timestamp: ${data.timestamp}`, 14, currentY);
  currentY += 6;
  doc.text(`GPS Coordinates: ${data.location.lat.toFixed(6)}, ${data.location.lng.toFixed(6)}`, 14, currentY);
  currentY += 6;
  doc.text(`Detection Method: ${data.detectionMethod}`, 14, currentY);
  currentY += 15;

  // Section 2: AI Triage
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('2. AI Triage Summary', 14, currentY);
  currentY += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Severity Level: ${data.aiTriage.severity}`, 14, currentY);
  doc.text(`Confidence: ${data.aiTriage.confidence}%`, pageWidth / 2, currentY);
  currentY += 6;
  doc.text(`Recommended Unit: ${data.aiTriage.recommendedUnit}`, 14, currentY);
  currentY += 6;
  doc.text(`Summary: ${data.aiTriage.summary}`, 14, currentY, { maxWidth: pageWidth - 28 });
  currentY += 15;

  // Section 3: Response Timeline
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('3. Response Timeline', 14, currentY);
  currentY += 5;

  autoTable(doc, {
    startY: currentY,
    head: [['Time', 'Event', 'Responder', 'Status']],
    body: data.timeline.map(t => [t.time, t.event, t.responder, t.status]),
    theme: 'striped',
    headStyles: { fillColor: [0, 51, 153] },
  });

  currentY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;

  // Section 4: Dispatched Resources
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('4. Dispatched Resources', 14, currentY);
  currentY += 5;

  autoTable(doc, {
    startY: currentY,
    head: [['Hospital/Unit', 'Type', 'Est. ETA', 'Actual Arrival', 'Resp. Time']],
    body: data.resources.map(r => [r.name, r.type, r.eta, r.actualArrival, r.responseTime]),
    theme: 'grid',
    headStyles: { fillColor: [0, 51, 153] },
  });

  currentY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;

  // Section 5: Victim Data
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('5. Victim Assessment (Anonymized)', 14, currentY);
  currentY += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Age Range: ${data.victimData.ageRange}`, 14, currentY);
  currentY += 6;
  doc.text(`Consciousness: ${data.victimData.consciousness}`, 14, currentY);
  currentY += 6;
  doc.text(`Identified Injuries: ${data.victimData.injuries.join(', ')}`, 14, currentY, { maxWidth: pageWidth - 28 });

  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      'Generated by ROADSoS — Road Safety Hackathon 2026, IIT Madras',
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  doc.save(`ROADSOS_REPORT_${data.id}.pdf`);
};
