import jsPDF from 'jspdf';
import autoTable, { type UserOptions } from 'jspdf-autotable';
import { format } from 'date-fns';

export interface InsuranceClaimData {
  incidentId: string;
  timestamp: number;
  location: { lat: number; lng: number };
  vaahan: {
    plate: string;
    model: string;
    owner: string;
    insurance: string;
    puc: string;
  };
  telemetry: {
    speed: number;
    gForce: { x: number; y: number; z: number };
    impactAngle: string;
    weather: string;
    roadType: string;
  };
  triage: {
    severity: string;
    confidence: number;
    summary: string;
    injuries: string[];
    driverBehaviorScore: number;
  };
  evidence: {
    bystanderReports: number;
    photosTaken: number;
    witnessCount: number;
  };
  timeline: Array<{
    time: string;
    event: string;
    responder: string;
    status: string;
  }>;
}

interface JspdfWithAutotable extends jsPDF {
  lastAutoTable: {
    finalY: number;
  };
}

export const generateClaimPDF = async (data: InsuranceClaimData) => {
  const doc = new jsPDF() as JspdfWithAutotable;
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 14;

  const claimRef = `RSC-${data.incidentId.substring(0, 8).toUpperCase()}-2026`;

  // --- HELPER: HEADER ---
  const addHeader = (title: string) => {
    doc.setFillColor(0, 51, 153);
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin, 20);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Ref: ${claimRef}`, margin, 30);
    doc.text('PRE-FILLED BY ROADSOS AI', pageWidth - margin, 30, { align: 'right' });
  };

  // --- PAGE 1: POLICY & DECLARATION ---
  addHeader('MOTOR ACCIDENT INSURANCE CLAIM');
  
  let currentY = 55;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('1. POLICYHOLDER & VEHICLE DETAILS', margin, currentY);
  currentY += 10;

  autoTable(doc, {
    startY: currentY,
    head: [['Field', 'Information']],
    body: [
      ['Registration No.', data.vaahan.plate],
      ['Vehicle Model', data.vaahan.model],
      ['Owner Name', data.vaahan.owner],
      ['Insurance Policy', data.vaahan.insurance],
      ['PUC Status', data.vaahan.puc],
      ['Incident ID', data.incidentId]
    ],
    theme: 'grid',
    headStyles: { fillColor: [0, 51, 153] },
    margin: { left: margin, right: margin }
  } as UserOptions);

  currentY = doc.lastAutoTable.finalY + 20;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('LEGAL DECLARATION', margin, currentY);
  currentY += 10;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const declaration = "This document is automatically generated by the ROADSoS Emergency Ecosystem. The data contained herein is derived from real-time vehicle telemetry, smartphone sensors, and AI-driven triage evaluations recorded at the time of the incident. This report serves as an official preliminary claim documentation for insurance processing. Any tampering with this AI-certified report may constitute insurance fraud.";
  doc.text(declaration, margin, currentY, { maxWidth: pageWidth - 28, align: 'justify' });

  // --- PAGE 2: INCIDENT TELEMETRY ---
  doc.addPage();
  addHeader('INCIDENT TELEMETRY & CONTEXT');
  currentY = 55;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('2. TELEMETRY LOGS (AT IMPACT)', margin, currentY);
  currentY += 10;

  autoTable(doc, {
    startY: currentY,
    head: [['Metric', 'Value', 'Unit/Context']],
    body: [
      ['Incident Date/Time', format(new Date(data.timestamp), 'yyyy-MM-dd HH:mm:ss'), 'Local Time'],
      ['GPS Location', `${data.location.lat.toFixed(6)}, ${data.location.lng.toFixed(6)}`, 'Geographic Coordinates'],
      ['Impact Speed', `${data.telemetry.speed} km/h`, 'From accelerometer/GPS'],
      ['Peak G-Force', `${data.telemetry.gForce.x.toFixed(2)}G (X), ${data.telemetry.gForce.y.toFixed(2)}G (Y)`, 'Crash severity marker'],
      ['Impact Angle', data.telemetry.impactAngle, 'Vector analysis'],
      ['Weather Condition', data.telemetry.weather, 'Recorded at scene'],
      ['Road Type', data.telemetry.roadType, 'Map-matching data']
    ],
    theme: 'striped',
    headStyles: { fillColor: [0, 51, 153] }
  } as UserOptions);

  // --- PAGE 3: DAMAGE & INJURY ASSESSMENT ---
  doc.addPage();
  addHeader('DAMAGE & INJURY ASSESSMENT');
  currentY = 55;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('3. AI TRIAGE & CLINICAL SUMMARY', margin, currentY);
  currentY += 10;

  autoTable(doc, {
    startY: currentY,
    head: [['Assessment Metric', 'Result']],
    body: [
      ['Triage Severity', data.triage.severity],
      ['AI Confidence Score', `${data.triage.confidence}%`],
      ['Driver Behavior Score', `${data.triage.driverBehaviorScore}/100`],
      ['Identified Injuries', data.triage.injuries.join(', ')]
    ],
    theme: 'grid',
    headStyles: { fillColor: [0, 51, 153] }
  } as UserOptions);

  currentY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('CLINICAL SUMMARY:', margin, currentY);
  currentY += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(data.triage.summary, margin, currentY, { maxWidth: pageWidth - 28 });

  // --- PAGE 4: EVIDENCE & WITNESSES ---
  doc.addPage();
  addHeader('EVIDENCE & WITNESS REPORTS');
  currentY = 55;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('4. DIGITAL EVIDENCE LOG', margin, currentY);
  currentY += 10;

  autoTable(doc, {
    startY: currentY,
    head: [['Evidence Type', 'Count/Status']],
    body: [
      ['Bystander Reports', data.evidence.bystanderReports],
      ['Witnesses Identified', data.evidence.witnessCount],
      ['Scene Photos Captured', data.evidence.photosTaken],
      ['Blackbox Data Status', 'ENCRYPTED & SYNCED'],
      ['Audio/Voice SOS Logs', 'AVAILABLE ON REQUEST']
    ],
    theme: 'striped',
    headStyles: { fillColor: [0, 51, 153] }
  } as UserOptions);

  currentY = doc.lastAutoTable.finalY + 20;
  doc.setDrawColor(200, 200, 200);
  doc.rect(margin, currentY, (pageWidth - 2 * margin) / 2 - 5, 60);
  doc.text('PHOTO 1: SCENE OVERVIEW', margin + 5, currentY + 35);
  
  doc.rect(pageWidth / 2 + 5, currentY, (pageWidth - 2 * margin) / 2 - 5, 60);
  doc.text('PHOTO 2: VEHICLE DAMAGE', pageWidth / 2 + 10, currentY + 35);

  // --- PAGE 5: RESPONSE TIMELINE ---
  doc.addPage();
  addHeader('OFFICIAL RESPONSE TIMELINE');
  currentY = 55;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('5. EVENT SEQUENCE', margin, currentY);
  currentY += 10;

  autoTable(doc, {
    startY: currentY,
    head: [['Timestamp', 'Event Description', 'Acting Agency', 'Status']],
    body: data.timeline.map(t => [t.time, t.event, t.responder, t.status]),
    theme: 'grid',
    headStyles: { fillColor: [0, 51, 153] }
  } as UserOptions);

  // --- FOOTER FOR ALL PAGES ---
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} — ROADSoS AI-Verified Claim Report — Generated on ${format(new Date(), 'yyyy-MM-dd HH:mm')}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  doc.save(`ROADSOS_CLAIM_${data.incidentId.substring(0, 8)}.pdf`);
};
